# Generated by Django 6.0.2 on 2026-03-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description_fr', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcdO3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description_fr', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('topography', 'Topography'), ('morphology', 'Morphology')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nid', models.CharField(max_length=20)),
                ('snapshot_data', models.JSONField(verbose_name='Données historiques (Document A/B)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, help_text="Numéro d'enregistrement du registre", max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de jeune fille')),
                ('gender', models.IntegerField(choices=[(1, 'Masculin'), (2, 'Féminin'), (9, 'Inconnu')], default=9, verbose_name='Sexe')),
                ('birth_date', models.CharField(help_text='DD/MM/YYYY (99 = inconnu)', max_length=10, verbose_name='Date de naissance')),
                ('nid', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='NID (Identifiant National)')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Sécurité Sociale')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('nationality', models.CharField(default='Algérienne', max_length=50, verbose_name='Nationalité')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ethnie/Groupe')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('W', 'Veuf/Veuve'), ('U', 'Inconnu')], max_length=1, null=True, verbose_name='Statut matrimonial')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name="Niveau d'éducation")),
                ('income_bracket', models.CharField(blank=True, max_length=50, null=True, verbose_name='Revenu/CSP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact d'urgence")),
                ('address_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse ligne 1')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse ligne 2')),
                ('vital_status', models.CharField(choices=[('A', 'Vivant'), ('D', 'Décédé'), ('U', 'Inconnu')], default='U', max_length=1)),
                ('date_of_death', models.CharField(blank=True, help_text='DD/MM/YYYY (99 = inconnu)', max_length=10, null=True)),
                ('cause_of_death_icd10', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cause de décès (CIM-10)')),
                ('autopsy', models.CharField(blank=True, choices=[('Y', 'Oui'), ('N', 'Non'), ('U', 'Inconnu')], max_length=1, null=True, verbose_name='Autopsie')),
                ('last_contact_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date dernier contact')),
                ('record_status', models.CharField(choices=[('0', 'En attente'), ('1', 'Vérifié'), ('2', 'Archivé')], default='0', max_length=1, verbose_name='Statut du dossier')),
                ('check_status', models.CharField(choices=[('Unchecked', 'Non vérifié'), ('OK', 'Conforme'), ('Rare', 'Rare'), ('Invalid', 'Invalide')], default='Unchecked', max_length=20, verbose_name='Statut de vérification')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modifié par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.commune')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Personnel', 'Personnel'), ('Familial', 'Familial'), ('Chirurgical', 'Chirurgical')], max_length=20)),
                ('category', models.CharField(choices=[('Antécédents', 'Antécédents'), ('Allergie', 'Allergie'), ('Comorbidité', 'Comorbidité')], max_length=20)),
                ('description', models.CharField(max_length=255, verbose_name='Description structurée')),
                ('date_noted', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='registry.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MergedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confidence', models.CharField(max_length=50, verbose_name='Confiance (Exact, Soundex)')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.CharField(default='Auto-Merge Engine', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Merge is active (un-merged if False)')),
                ('surviving_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges', to='registry.patient')),
                ('document_a_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_as_a', to='registry.patientrevision')),
                ('document_b_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_as_b', to='registry.patientrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacovigilance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_description', models.TextField()),
                ('grade', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'Décès')])),
                ('is_serious', models.BooleanField(default=False)),
                ('date_onset', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='registry.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence_date', models.CharField(help_text='DD/MM/YYYY', max_length=10, verbose_name="Date d'incidence")),
                ('date_of_last_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('topo_code', models.CharField(help_text='Ex: C34.1', max_length=5, verbose_name='Topographie (CIM-O-3)')),
                ('morpho_code', models.CharField(help_text='Ex: 8070/3', max_length=6, verbose_name='Morphologie (CIM-O-3)')),
                ('behaviour', models.CharField(choices=[('0', '/0 Bénin'), ('1', '/1 Incertain'), ('2', '/2 In situ'), ('3', '/3 Malin'), ('6', '/6 Malin, métastatique'), ('9', '/9 Malin, incertain')], max_length=1, verbose_name='Comportement (/0-/3)')),
                ('grade', models.CharField(choices=[('1', 'G1 – Bien différencié'), ('2', 'G2 – Modérément'), ('3', 'G3 – Peu différencié'), ('4', 'G4 – Indifférencié / anaplasique'), ('5', 'T-cell'), ('6', 'B-cell'), ('8', 'NK-cell'), ('9', 'Non déterminé')], default='9', max_length=1, verbose_name='Grade / Différenciation')),
                ('icd10_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Conversion CIM-10')),
                ('basis_of_diagnosis', models.CharField(choices=[('0', '0 – DCO (Certificat de décès uniquement)'), ('1', '1 – Clinique'), ('2', '2 – Recherche clinique (Imagerie, Endoscopie, Chirurgie exploratoire)'), ('4', '4 – Marqueurs tumoraux spécifiques'), ('5', '5 – Cytologie / Hématologie'), ('6', '6 – Histologie de la métastase'), ('7', '7 – Histologie de la tumeur primitive'), ('8', '8 – Autopsie avec histologie'), ('9', '9 – Inconnu')], default='9', max_length=1, verbose_name='Base du diagnostic')),
                ('laterality', models.CharField(choices=[('0', 'Non applicable'), ('1', 'Droite'), ('2', 'Gauche'), ('3', 'Bilatéral'), ('4', 'Origine unique, bilatéral'), ('9', 'Inconnu')], default='0', max_length=1, verbose_name='Latéralité')),
                ('clinical_t', models.CharField(blank=True, max_length=5, null=True, verbose_name='cT')),
                ('clinical_n', models.CharField(blank=True, max_length=5, null=True, verbose_name='cN')),
                ('clinical_m', models.CharField(blank=True, max_length=5, null=True, verbose_name='cM')),
                ('clinical_stage_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Stade clinique (I-IV)')),
                ('pathological_t', models.CharField(blank=True, max_length=5, null=True, verbose_name='pT')),
                ('pathological_n', models.CharField(blank=True, max_length=5, null=True, verbose_name='pN')),
                ('pathological_m', models.CharField(blank=True, max_length=5, null=True, verbose_name='pM')),
                ('pathological_stage_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Stade pathologique (I-IV)')),
                ('tnm_edition', models.CharField(default='8', help_text='7 ou 8', max_length=2, verbose_name='Édition TNM')),
                ('tumor_size', models.IntegerField(blank=True, null=True, verbose_name='Taille tumeur (mm)')),
                ('diagnostic_status', models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', 'Confirmé'), ('Inconnu', 'Inconnu'), ('Inclassable', 'Inclassable')], default='En attente', max_length=20, verbose_name='État du Diagnostic')),
                ('histology_detail', models.TextField(blank=True, null=True, verbose_name='Détails Histologiques')),
                ('who_classification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Classification OMS')),
                ('mp_code', models.CharField(default='00', help_text='00=unique, 01-09=séquence', max_length=2, verbose_name='Code MP')),
                ('is_most_valid', models.BooleanField(default=True, verbose_name='Diagnostic le plus valide')),
                ('tumour_number', models.IntegerField(default=1, verbose_name='N° Tumeur pour ce patient')),
                ('treatment_1', models.CharField(choices=[('0', 'Aucun'), ('1', 'Chirurgie'), ('2', 'Radiothérapie'), ('3', 'Chimiothérapie'), ('4', 'Hormonothérapie'), ('5', 'Immunothérapie'), ('6', 'Thérapie ciblée'), ('7', 'Combinaison'), ('8', 'Autre'), ('9', 'Inconnu')], default='9', max_length=1, verbose_name='Traitement principal')),
                ('treatment_2', models.CharField(blank=True, choices=[('0', 'Aucun'), ('1', 'Chirurgie'), ('2', 'Radiothérapie'), ('3', 'Chimiothérapie'), ('4', 'Hormonothérapie'), ('5', 'Immunothérapie'), ('6', 'Thérapie ciblée'), ('7', 'Combinaison'), ('8', 'Autre'), ('9', 'Inconnu')], max_length=1, null=True, verbose_name='Traitement secondaire')),
                ('date_of_treatment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date du traitement')),
                ('check_status', models.CharField(choices=[('Unchecked', 'Non vérifié'), ('OK', 'Conforme'), ('Rare', 'Rare'), ('Invalid', 'Invalide')], default='Unchecked', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumors', to='registry.patient')),
            ],
            options={
                'ordering': ['-incidence_date'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('HP', 'Histopathologie'), ('CY', 'Cytologie'), ('HE', 'Hématologie'), ('CL', 'Clinique'), ('IM', 'Imagerie'), ('DC', 'DCO (Certificat décès)'), ('AU', 'Autopsie'), ('RT', 'Registre des tumeurs (échange)'), ('LA', 'Laboratoire (marqueurs)'), ('OT', 'Autre')], max_length=2, verbose_name='Type de source')),
                ('source_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description de la source')),
                ('hospital_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code établissement')),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'établissement")),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service')),
                ('report_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de rapport')),
                ('date_of_report', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date du rapport')),
                ('practitioner_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Praticien / Pathologiste')),
                ('reader_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agent / Lecteur')),
                ('clinical_text', models.TextField(blank=True, null=True, verbose_name='Texte clinique')),
                ('pathology_text', models.TextField(blank=True, null=True, verbose_name='Texte pathologique')),
                ('date_received', models.DateField(auto_now_add=True)),
                ('tumor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='registry.tumor')),
            ],
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50, verbose_name='Nom du test (ex: HER2, EGFR, Ki-67)')),
                ('result_value', models.CharField(max_length=50, verbose_name='Résultat (ex: Positif, Négatif, 3+, Muté)')),
                ('percentage', models.IntegerField(blank=True, null=True, verbose_name='Pourcentage (ex: 80 pour 80%)')),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('tumor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers', to='registry.tumor')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='registry.wilaya'),
        ),
        migrations.CreateModel(
            name='WilayaPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('age_group', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(1, 'Masculin'), (2, 'Féminin')])),
                ('count', models.IntegerField()),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.wilaya')),
            ],
            options={
                'unique_together': {('wilaya', 'year', 'age_group', 'gender')},
            },
        ),
    ]
