# Generated by Django 6.0.2 on 2026-03-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Ex: Cardiaque, Gastro-intestinal', max_length=100)),
                ('term', models.CharField(help_text='Ex: Tachycardie, Nausée', max_length=200)),
                ('grade_0', models.TextField(blank=True, null=True, verbose_name='Grade 0 (Absent)')),
                ('grade_1', models.TextField(blank=True, null=True, verbose_name='Grade 1 (Léger)')),
                ('grade_2', models.TextField(blank=True, null=True, verbose_name='Grade 2 (Modéré)')),
                ('grade_3', models.TextField(blank=True, null=True, verbose_name='Grade 3 (Sévère)')),
                ('grade_4', models.TextField(blank=True, null=True, verbose_name='Grade 4 (Menace le pronostic vital)')),
                ('grade_5', models.TextField(blank=True, null=True, verbose_name='Grade 5 (Décès)')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ETAT', 'État Dossier'), ('CTRL', 'Contrôles'), ('DBL', 'Doublons'), ('TOPO', 'Localisation'), ('VITAL', 'Statut Vital'), ('BASIS', 'Base du Diagnostic'), ('CAUSE', 'Cause de Décès'), ('PLACE', 'Lieu de Décès'), ('ENQ', 'Enquêteur'), ('LAB', 'Laboratoire'), ('SERV', 'Service')], max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medical Dictionaries',
                'unique_together': {('section', 'code')},
            },
        ),
    ]
