# Generated by Django 6.0.2 on 2026-03-11 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_toxicitycriteria_medicaldictionary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('smoking_status', models.CharField(choices=[('Never', 'Jamais'), ('Former', 'Ex-fumeur'), ('Current', 'Fumeur Actuel')], default='Never', max_length=50)),
                ('cigarettes_per_day', models.IntegerField(default=0)),
                ('years_smoking', models.IntegerField(default=0)),
                ('alcohol_consumption', models.CharField(choices=[('None', 'Aucune'), ('Occasional', 'Occasionnel'), ('Frequent', 'Fréquent')], default='None', max_length=50)),
                ('dietary_habits', models.TextField(blank=True, help_text='Consommation de viande rouge, sel, sucre, etc.', null=True)),
                ('physical_activity', models.CharField(choices=[('Sedentary', 'Sédentaire'), ('Moderate', 'Modéré'), ('Active', 'Actif')], default='Sedentary', max_length=50)),
                ('occupational_exposure', models.TextField(blank=True, help_text='Amiante, produits chimiques, etc.', null=True)),
                ('family_cancer_history', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitudes', to='registry.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Registraire (Admin)'), ('DOCTOR', 'Médecin'), ('ANAPATH', 'Anapath'), ('LAB', 'Laboratoire')], default='DOCTOR', max_length=10)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.wilaya')),
            ],
        ),
    ]
