# Generated by Django 6.0.2 on 2026-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_dynamicformconfig_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='workflow',
            field=models.CharField(choices=[('clinique', 'En attente'), ('anapath', 'En validation'), ('valide', 'Complet')], default='clinique', max_length=20, verbose_name='Statut du Workflow'),
        ),
    ]
