# Generated by Django 6.0.2 on 2026-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_patient_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitquestionnaire',
            name='alcohol_type',
            field=models.CharField(blank=True, help_text='Vin, Bière, Spiritueux, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='cigar_use',
            field=models.BooleanField(default=False, verbose_name='Usage de Cigare'),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='exercise_hours_weekly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='fruit_veg_daily',
            field=models.IntegerField(default=0, help_text='Portions de fruits/légumes par jour'),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='hookah_use',
            field=models.BooleanField(default=False, verbose_name='Usage de Chicha'),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='other_chronic_diseases',
            field=models.TextField(blank=True, help_text='Diabète, HTA, Maladies auto-immunes, etc.', null=True),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='pollution_exposure',
            field=models.BooleanField(default=False, help_text='Vit/Travaille en zone très polluée'),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='processed_meat_freq',
            field=models.CharField(choices=[('Never', 'Jamais'), ('Rarely', 'Rarement'), ('Weekly', 'Hebdomadaire'), ('Daily', 'Quotidien')], default='Never', max_length=50),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='sleep_hours',
            field=models.IntegerField(default=7, help_text='Heures de sommeil moyennes par nuit'),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='stress_level',
            field=models.CharField(choices=[('Low', 'Faible'), ('Moderate', 'Modéré'), ('High', 'Élevé')], default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='sun_exposure',
            field=models.CharField(choices=[('Low', 'Faible'), ('Moderate', 'Modéré'), ('High', 'Élevé')], default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='habitquestionnaire',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitquestionnaire',
            name='family_cancer_history',
            field=models.TextField(blank=True, help_text='Détails des cancers familiaux (Types et Degrés de parenté)', null=True),
        ),
        migrations.AlterField(
            model_name='habitquestionnaire',
            name='occupational_exposure',
            field=models.TextField(blank=True, help_text='Amiante, produits chimiques, solvants, etc.', null=True),
        ),
    ]
