# Generated by Django 6.0.2 on 2026-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_personalizedmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedmap',
            name='zones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
