# Generated by Django 6.0.2 on 2026-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_add_zones_to_personalized_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Registraire (Admin)'), ('DOCTOR', 'Médecin'), ('ANAPATH', 'Anapath'), ('LAB', 'Laboratoire'), ('DIRECTOR', 'Directeur'), ('ANALYST', 'Analyste / Épidémiologiste')], default='DOCTOR', max_length=10),
        ),
    ]
