services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=registre_db
      - POSTGRES_USER=registre_user
      - POSTGRES_PASSWORD=registre_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U registre_user -d registre_db"]
      interval: 20s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
